### ISSUE TITLE
Improve XLS report - add statistics

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rrybalkin/vouchers#8] opened 2015-09-23 18:32 UTC
```
Need to add final amount of dinners, lunches and prices.
```

Original issue reported on code.google.com by `Roman.Ry...@gmail.com` on 18 Oct 2014 at 5:04

**Comment by rrybalkin** [comment] 2018-09-27 21:14
Closed as a duplicate of #14

**Closed as completed** 2018-09-27 21:14 UTC
Labels: Priority-Medium, auto-migrated, Type-Task
